### ISSUE TITLE
Automate detection of module conflicts

### ISSUE THREAD

**Issue by goldingn** [zoonproject/zoon#95] opened 2015-08-19 10:09 UTC
A bunch of the bugs here arise from casually noticing that a particular combination of modules doesn't work.

It might be worth writing some code automate this process by picking random combinations (an exhaustive list would probably be unmanageable) of modules (including lists/chains) and report those which throw errors.

What do you think?

**Comment by AugustT** [comment] 2016-02-17 14:44
So the aim is to detect module conflicts?

We already have testing in place that ensures that a module outputs objects in the format that they are supposed to, this should catch the majority of conflicts where they exist. 

As you say an exhaustive check is really not possible.

I'm going to add tests for modules that place them in workflows. However this will be placing 1 unknown/new module in a workflow with 4 other established module. So testing new (not written by us) modules with others would not be covered.

Now that datatype tags are in place it would be possible to randomly put modules together in a way which means they should work. I don't think this is the way to go as it is too 'random'.

I think this is a duplicate of #159

**Closed by AugustT** 2016-02-17 14:44 UTC
Labels: question
