### ISSUE TITLE
Fix BuildModule

### ISSUE THREAD

**Issue by goldingn** [zoonproject/zoon#158] opened 2015-09-15 10:04 UTC
With all of the changes for the workshop, `BuildModule` and its docs are no longer in sync with the rest of zoon. It needs:

- [x] `ZoonModel` usage explained in the doc
- [x] a `@family` tag added automatically based on the module type
- [x] tests to be written

**Comment by goldingn** [comment] 2015-09-15 10:11
see also #82 from the first hack fday

**Comment by AugustT** [comment] 2015-10-05 09:07
@goldingn your commit history is hilarious!

**Comment by goldingn** [comment] 2015-10-05 09:37
When I was trying to get Travis to work? Yeah I lost it there for a bit...

**Comment by AugustT** [comment] 2015-10-05 11:33
@family has issues as there is a bug in Roxygen2. I have fixed the bug and put in a pull request here:

https://github.com/klutometis/roxygen/pull/383

**Comment by AugustT** [comment] 2015-10-07 13:21
Hey @goldingn,

I'm trying to fully understand `ZoonModel`. I think I get most of it but one thing still confuses me. 

Say I have 2 model models. One uses `gam` so the object returned already has a predict method. One is custom so I create my predict method using `ZoonModel`.

At some point in the zoon workflow [in `RunModel` I think] i expect there to be a statement like this (in pseudo code):

```
If(model has predict method){
    pred <- predict(model)
} else if(model has ZoonModel prediction){
    pred <- ZoonPredict(model)
} else {
   stop('no predict method')
}
```

but I can't find it. At the moment it looks like everything goes to ZoonPredict which I think can only handle things with ZoonModel custom predicts. Let me know where I have gone wrong!

Tom

**Comment by AugustT** [comment] 2015-10-07 13:23
Ahhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh, I get it now! Every model module returns a ZoonModel object.... sorry, typically I figured it out just after I sent the messge

**Comment by goldingn** [comment] 2015-10-07 14:02
yup, has to be this way to force all predict methods to have the same outputs. E.g. `GRaF`'s predict method returns a matrix

**Comment by goldingn** [comment] 2015-10-07 14:09
btw those checkboxes in the first message are cool - didn't know you could do that

**Comment by AugustT** [comment] 2015-10-07 14:16
Yeah, I find them really handy for issues which have multiple elements, helps people to see progress through an issue.

**Comment by AugustT** [comment] 2015-10-07 14:42
My PR to roxygen has been excepted by Hadley so with the next release the issues with raster and the family tag should go

**Comment by AugustT** [comment] 2015-10-12 14:41
tests have now been written for build module, closing

**Comment by goldingn** [comment] 2015-10-12 21:26
Just to note that #82 is still open...

**Comment by AugustT** [comment] 2015-10-13 08:27
sure, just closed this because the listed tasks were complete, I'll get to #82

**Comment by goldingn** [comment] 2015-10-13 14:15
Looks like there's a fairly major bug in `BuildModule`, @AugustT. It doesn't return the function definition in the file!:

```r
obj <- function(param){
  message(param)
}

BuildModule(obj,
            type = 'occurrence',
            title = 'title',
            description = 'description',
            details = 'details',
            author = 'author author',
            email = 'e@mail.com',
            paras = list(param = 'param'),
            dir = tempdir())

fpath <- file.path(tempdir(), 'obj.R')
writeLines(readLines(fpath))
```
```
#' @name obj
#'
#' @title title
#'
#' @description description
#'
#' @details Module type: Occurrence
#' details
#'
#'@param param param
#'
#' @family occurrence
#'
#' @author author author
#'
#' @author e@@mail.com
#'
#' @name obj
obj <-
"obj"
```

Looks like it's just because the penultimate line in `BuildModule` should use `object` rather than `obj`.

Also, there are two `@name` tags!

**Comment by AugustT** [comment] 2015-10-13 15:04
Shoddy workmanship

**Comment by AugustT** [comment] 2015-10-13 15:10
Try this:

```r
NewName <- function(param){
  message(param)
}

BuildModule(NewName,
            type = 'occurrence',
            title = 'title',
            description = 'description',
            details = 'details',
            author = 'author author',
            email = 'e@mail.com',
            paras = list(param = 'param'))
```

**Comment by AugustT** [comment] 2015-10-13 15:11
I think this is a duplicate of #190

**Comment by goldingn** [comment] 2015-10-13 15:13
Huh, yeah it only fails with `obj`

**Comment by AugustT** [comment] 2015-10-13 16:01
Closing as a replicate of #190

**Closed by AugustT** 2015-10-13 16:01 UTC
Labels: bug
