### ISSUE TITLE
ResponseCurveViz

### ISSUE THREAD

**Issue by AugustT** [zoonproject/zoon#367] opened 2017-02-06 11:53 UTC
I can't get this module to work. Whenever I use it in a workflow I get 

```r
Error in parse(text = rawText) : <text>:24:58: unexpected input
23: #' @section Date submitted:  2016-06-15
24: ResponseCurveViz <- function (.model, .ras, cov = NULL) {
                                                             ^
```

But I can source the raw version on github no problem. Can't figure it out at the moment

**Comment by AugustT** [comment] 2017-02-07 10:05
It appears that this module has `\r`  at the end of each line. I don't know much about line returns but this causes an error on my windows machine. Presumably these have been put in be a linux of mac? This might need some changes to `BuildModule` to make sure this issue does not occur in the future.

**Comment by AugustT** [comment] 2017-02-07 10:06
Need to make sure this is not in other modules too

**Comment by timcdlucas** [comment] 2017-02-07 10:13
Linux line return is \n. I thought \r is windows (though turns out it's more complicated that I thought). There's something about \r\n being the proper new line.

It may well be a linux or mac machine accidentally adding an extra line ending thinking it's helping or something.

**Comment by goldingn** [comment] 2017-02-07 10:16
\r is a carriage return. Windows uses both a carriage return and a newline by default (like a typewriter).
This had windows line nedings and for some reason they suddenly started causing problems.

I just merged a fix, here's a reproducible example:

```r
library(zoon)
# the old version of the repo doesn't work
options(zoonRepoBranch = '433253668c343525ca9068605efe4c56540ca17c')
LoadModule('ResponseCurveViz')
```
```
Error in parse(text = getURL(zoonURL, ssl.verifypeer = FALSE)) : 
  <text>:24:58: unexpected input
23: #' @section Date submitted:  2016-06-15
24: ResponseCurveViz <- function (.model, .ras, cov = NULL) {
```

```r
# the current version of the repo does
options(zoonRepoBranch = 'master')
LoadModule('ResponseCurveViz')
```
```
[1] "ResponseCurveViz"
```

**Comment by goldingn** [comment] 2017-02-07 10:29
I just found and fixed the same line ending problem in two more modules: `NBNdataByName` & `VariableImportance`

For the record, I found the dodgy files with this bash:
```
grep -r '^M' .
```
and then used these commands to delete the carriage returns in vim:
```
:e ++ff=unix
:%s/^M//g
```

**Closed** 2017-02-07 10:31 UTC
